#
# Copyright (C) 2024-2026 XIAOZHAOXSXH
#
# This is free software, licensed under the MIT License.
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI 5G CPE View - Huawei 5G Modem Web Panel
LUCI_DEPENDS:=
LUCI_PKGNAME:=luci-app-5g-cpe-view

PKG_NAME:=luci-app-5g-cpe-view
PKG_VERSION:=1.0.0
PKG_RELEASE:=1

PKG_MAINTAINER:=XIAOZHAOXSXH
PKG_LICENSE:=MIT

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
$(eval $(call BuildPackage,luci-app-5g-cpe-view))
